name: scheduled Workflow
on:
  schedule:
    - cron: "17 13 * * *" # Runs every day at midnight UTC
jobs:
  ScheduledTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - name: Run tests
        run: echo "Scheduled test run"
